[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r backend/minimal_requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && python simple_main.py"
